### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by BTruer** [lucasepe/jumble#1]
Hi. Looks like a cool new OS project! That's a great idea to take Infra as Code and be able to make diagrams from them. I don't see robost documentation or a readthedocs page. Is this planned?

**Comment by lucasepe** [comment]
Hi! Thanks! Yes! Absolutely! I'll start to write docs and release with the v0. 2.0 in about a couple of weeks

**Comment by BTruer** [comment]
Sounds great! looking forward to it
